sudo: required

language: python3

services:
  - docker

before_install:
  - docker build -t logic .
  - docker run -d --name logic logic

script: docker exec -t logic /etc/twine-package-manager-logic/vendor/bin/phpunit --configuration /etc/twine-package-manager-logic/phpunit.xml