sudo: required

language: generic

branches:
  - master

services:
  - docker

install:
  - docker build -t logic .
  - docker run -d --name logic logic

script: docker exec -t logic vendor/bin/phpunit